

#==========================Prepare Image to be Build====================
FROM golang:1.21.3-alpine3.17 AS base
# Set destination for COPY
WORKDIR /app
# Download Go modules
COPY go.mod go.sum ./
RUN go mod download
# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . ./


#========================== Build Image ====================
FROM base AS build-server
RUN go build -o /bin/server cmd/main/main.go

FROM scratch  AS prod
COPY --from=build-server /bin/server /bin/
EXPOSE 8080
# Run
CMD ["./bin/server"]
