
version: "3"
services:
  postgresDB:
    container_name: postgresDB 
    # platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: dev.env
    image: postgres:12.0-alpine

    # ---- Defined in dev.env ----
    # environment:
    #   POSTGRES_USER: ${DATABASE_USERNAME}
    #   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    #   POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"
    networks:
      - postgresDB

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped 
    env_file: dev.env
    ports:
      - "5050:80"
    depends_on:
      - postgresDB
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgresDB

volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgresDB:
    name: Postgres 
    driver: bridge

